version: "3.8"

services:
  redis:
    image: redis:6.2.3-alpine
    restart: always
    container_name: posts_redis
    volumes:
      - posts_redis_data:/data:rw

  backend:
    build:
      context: .
    container_name: posts_backend
    ports:
      - 5000:5000
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  posts_redis_data:
    driver: local
    name: poll_system_redis_data
